use_frameworks!

platform :ios, '8.0'

target 'SWAlertController_Example' do
  pod 'SWAlertController2', :path => '../'
  
  pod 'YYKit',                  '1.0.9',          :inhibit_warnings => true
  pod 'Masonry',                '1.1.0',          :inhibit_warnings => true

  target 'SWAlertController_Tests' do
    inherit! :search_paths

    
  end
end
