use_frameworks!

platform :ios, '8.0'

target 'SWAlertController_Example' do
  pod 'SWAlertController', :path => '../'

  target 'SWAlertController_Tests' do
    inherit! :search_paths

    
  end
end
